version: "3"

services:

    webapp:
        build: .
        container_name: webapp
        restart: unless-stopped
        network_mode: host
        depends_on:
            - mysql
        environment:
            # set database, memcached etc credentials
            DB_HOST: 127.0.0.1
            DB_NAME: nmap
            DB_USER: nmapuser
            DB_PASSWORD: 123456
        ports:
            # bind on our 5000 port because most people have 80, 8080 already bound
            - "80:80"

    mysql:
        image: mysql:8.0.22
        restart: unless-stopped
        environment: 
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_USER: nmapuser
            MYSQL_PASSWORD: 123456
            MYSQL_DATABASE: nmap
        command: --default-authentication-plugin=mysql_native_password
        ports:
             - "127.0.0.1:3306:3306"

